### ISSUE TITLE
How to save cache locally and add `prefetch` option to getting faster resolve

### ISSUE THREAD

**Issue by quyleanh** [klutchell/unbound-docker#106]
Since I use with Adguard Home, everytime I update Adguard Home and restart docker image, the cache is gone.

I would like to save cache locally and prefetch the cache before it expires to get faster query on client side.

How can I archive it? Thank you.

**Comment by klutchell** [comment]
Unbound does not cache to disk, only to memory. Caching to disk would be much slower and reading the cache would often not be as fast as resolving again.

Why not keep the unbound container running and only restart the Adguard Home container?

**Comment by quyleanh** [comment]
Thank you for your answer.

I'm not sure if it can backup these caches to disk too. For example we force save cache to disk before stopping unbound and load cache to memory when starting. Can we do that?

It's my bad since I think I have to restart all services at once. But the cache is still gone when we update unbound, isn't it?

**Comment by churchofnoise** [comment]
It is typically gone after restarting Unbound indeed.

In the past, I've played with this as well, using what's described here: https://abridge2devnull.com/posts/2016/03/unbound-dns-server-cache-control/

In reality, the impact was minimal as cache build up fairly fast again.

In my current setup, pi-hole (equivalent of adguard for you) and unbound can be updated and restarted individually.
Perhaps something to consider...

**Comment by quyleanh** [comment]
@churchofnoise thank you for your information.

As I noticed, the initial query took about 200-300ms. How about yours?

I still don't understand the flow of building up cache which you mentioned. Could you please explain more detail?

**Comment by churchofnoise** [comment]
Initial queries take the same amount of time here.

Building up cache: I just mean, after a restart of Unbound, bit by bit, the cache is 'reconstructed'.
After a limited amount of time, your cache will contain the same elements as it did before.
So the net benefit of saving your cache to avoid loss during restart is probably limited.

(not completely related but might be interesting: you could increase your cache-min-ttl value to reduce query lookups once a domain is in your cache. I've been gradually increasing, starting at 3600 and bit by bit increasing. Currently at 86400 without any adverse effects, although one of them might be that you end up with a wrong IP address if it has changed during that period)

**Comment by quyleanh** [comment]
> Building up cache: I just mean, after a restart of Unbound, bit by bit, the cache is 'reconstructed'.
> After a limited amount of time, your cache will contain the same elements as it did before.
> So the net benefit of saving your cache to avoid loss during restart is probably limited.

So you mean the cache of all previous queries (the queries before restarting unbound) will be automatically reconstructed by prefetch?

About increasing min ttl number, thank you for your suggestion. As klutchell's unbound docker image has enabled `prefetch` by default, so I think it is not necessary to set a large min ttl number. (Am I right?)
For now, there is no problem about querying speed in my side, I will take a look when it does.

**Comment by churchofnoise** [comment]
> 



> So you mean the cache of all previous queries (the queries before restarting unbound) will be automatically reconstructed by prefetch?

No, I mean that the cache that was lost because of the restart, will come back after the first visit to each of those websites. So the slower queries will only occur during the first visit after restart. Not a big issue I'd say, and a couple of hundred ms will probably not be noticeable anyway.

> About increasing min ttl number, thank you for your suggestion. As klutchell's unbound docker image has enabled `prefetch` by default, so I think it is not necessary to set a large min ttl number. (Am I right?)

Correct, using prefetch brings the largest advantage in speed, increasing min ttl will not be noticeable to end users. It's more a matter of avoiding unnecessary queries and optimizing the use of cache.

**Comment by quyleanh** [comment]
> No, I mean that the cache that was lost because of the restart, will come back after the first visit to each of those websites. So the slower queries will only occur during the first visit after restart. Not a big issue I'd say, and a couple of hundred ms will probably not be noticeable anyway.

Ah, I get your point now. In my side, the cached queries is a bit faster than the new one, and it's noticeable.

Btw, thank you very much for explaining all these things patiently. I think I will close this issue since there is no suitable approach for me. Looking forward to seeing other idea.
