### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by vespino** [klutchell/unbound-docker#128]
Are queries cached inside the container? And is there a way of moving that cache to a volume so the cache isn’t lost when recreating the container? Maybe setting a max lifetime?

**Comment by klutchell** [comment]
Unbound caches to memory, so it cannot be easily mounted to a volume.

However there are commands to export and import cache data so you could
potentially use an external service to export the cache to a volume on
schedule and import it on startup, but it's beyond the scope of this image.

https://abridge2devnull.com/posts/2016/03/unbound-dns-server-cache-control/
