### ISSUE TITLE
which version should I use?

### ISSUE THREAD

**Issue by vespino** [klutchell/unbound-docker#144]
I usually tend to use :latest but I'm also seeing :main and a lot of other versions. What is the best and stable version?

**Comment by klutchell** [comment]
`latest` is the most stable and aligns with the most recent versioned tag.

`main` and similar branch names are from the tip of the branch. No need to
use these unless you are testing recently merged features.

**Comment by vespino** [comment]
Ok, playing safe and sticking with latest then. Cheers.
