### ISSUE TITLE
Add compile-time switch for EDNS Client Subnet Module Options (aka ECS)

### ISSUE THREAD

**Issue by TomTonic** [klutchell/unbound-docker#165]
The --enable-subnet switch of the configure script will enable the [EDNS Client Subnet Module Options](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#edns-client-subnet-module-options), see [explanation here](https://medium.com/nextdns/how-we-made-dns-both-fast-and-private-with-ecs-4970d70401e5), for example. Setting the compile-time switch would enable users to use ECS if they wish without adding extra dependencies, AFAIK.

**Comment by klutchell** [comment]
Sounds good to me, are you interested in opening a PR and testing it?

**Comment by TomTonic** [comment]
Interested - absolutely! But honestly, I am not yet familiar enough with that Docker stuff.

Here is how ECS can be tested:

`dig TXT o-o.myaddr.l.google.com +short @9.9.9.9`
`"<SOME_IP_ADDR>"` <-- A

`dig TXT o-o.myaddr.l.google.com +short @9.9.9.11 `
`"<SOME_IP_ADDR>"` <-- A
`"edns0-client-subnet <SOME_OTHER_IP_ADDR>/24"` <-- B

A: the source IP of a recursive resolver from Quad9 that sent the request to the authoritative name server `o-o.myaddr.l.google.com`
B: the class B or class C subnet of the computer where you executed the dig command

Notes:
- 9.9.9.9 is the public DNS resolver from Quad9 that explicitly does NOT pass ECS information
- 9.9.9.11 is the public DNS resolver from Quad9 that explicitly does pass ECS information
- sometimes the response lines for the second case (passing ECS information in the query) are in a different order
- the IP addresses A of consecutive calls may diverge

The unbound config needs the following lines to enable ECS:
`server:`                                                                                                                                                            
`    # Enable ECS`                                                                                                                                                 
`    module-config: "subnetcache validator iterator"`
`    # Send client source address to each and every authority. TODO: Find an actual list of IPs of CDN's`
`    send-client-subnet: 0.0.0.0/0`
`    send-client-subnet: ::0/64`

**Comment by churchofnoise** [comment]
Given the potential privacy issues, I would strongly suggest not including this in the standard config.
Users who desire so can easily enable it through a config file.

**Comment by klutchell** [comment]
> Given the potential privacy issues, I would strongly suggest not including this in the standard config. Users who desire so can easily enable it through a config file.

agreed, but the compile time option seems reasonable

**Comment by TomTonic** [comment]
> Given the potential privacy issues, I would strongly suggest not including this in the standard config.
> Users who desire so can easily enable it through a config file.

Absolutely, I agree. Requesting to change the default config wasn’t my intent. My second post was just about how this can be tested. This should definitely NOT be in the default config!

**Comment by klutchell** [comment]
We could make the ECS settings an example config override that is used for some tests, but not included in the final image.

This all seems pretty straightforward, including testing, I'll take a look when I get a chance.

**Comment by klutchell** [comment]
It is also a good chance to test config overrides in the test environment.

**Comment by klutchell** [comment]
This feature should now be available with the `klutchell/unbound:main` tag
