### ISSUE TITLE
Unbound stopped working after 1.14 update

### ISSUE THREAD

**Issue by BaukeZwart** [klutchell/unbound-docker#28]
Updated the container to 1.14 and now Adguard Home can no longer use unbound as upstream server.
Tried restarting  the container a few times.

The log isn't showing anything helpful.
Any idea how to fix this?

```
today at 09:32:29[1639470749] unbound[1:0] notice: init module 0: validator
today at 09:32:29[1639470749] unbound[1:0] notice: init module 1: iterator
today at 09:32:29[1639470749] unbound[1:0] info: start of service (unbound 1.14.0).
today at 09:32:29[1639470749] unbound[1:0] info: generate keytag query _ta-4a5c-4f66. NULL IN
```
I reverted back to 1.13.2 and unbound is working again

**Comment by RubenNL** [comment]
Can confirm, mine just stopped working after auto-updating, with the same log.
Reverting to 1.13.2 also fixed it for me.

I am running on a Oracle ARM server, i haven't tried on other hardware.

**Comment by BaukeZwart** [comment]
I'm running on a Synology 920+

**Comment by nikolak** [comment]
Are you using port `5053`? I had to change that port to `53` for it to work.

**Comment by BaukeZwart** [comment]
Thanks @nikolak that fixed it.
Strangely it doesn't seem to matter what port mapping you set in compose.
5053:5053 53:53 5053:53 all seem to work as long as I set xxx.xxx.xxx.xxx:53 in Adguard Home as upstream.

**Comment by RubenNL** [comment]
Fixed it for me too.
I changed this:
```
    ports:
      - '5053:5053/udp'
      - '5053:5053'
```
to 
```
    ports:
      - '5053:53/udp'
      - '5053:53'
```

My adguard home configuration uses `172.17.0.1:5053` as upstream resolver, which still works.

**Comment by klutchell** [comment]
Apologies folks, among the changes yesterday the default port switched from 5053 to 53. This was an oversight but now that it's been merged I think I prefer it that way for the default.

This shouldn't impact anyone that has mounted their own configuration volume. However if you are using the included default configuration the internal port mapping will need to change to 53.

**Comment by RubenNL** [comment]
Everyone makes mistakes, no problem :) Port 53 is indeed prefered.

Thanks for maintaining this repo.

Also thanks @BaukeZwart and @nikolak for the very quick fix.
