### ISSUE TITLE
What are/is Unbound’s default upstream servers?

### ISSUE THREAD

**Issue by vespino** [klutchell/unbound-docker#292]
I might be completely misunderstanding the use of Unbound, but does it use any upstream servers for DNS requests? Or is every request handled by Unbound and if not found it doesn’t look anywhere else? By default I’m not sending data to my ISP or Google or Quad9 or whatever?

Seeing as unbound-docker runs fine without any changes, what config changes can I think of making it run even better? Any howto’s?

**Comment by klutchell** [comment]
Unbound can use upstream DNS servers, but the default behaviour of the config included with this project is to recursively resolve all DNS locally via the root names. By default you are not sending any DNS requests to your ISP or Google or Quad9 when using this container.

As for other performance tweaks, I can only recommend reviewing the official docs as this is just a wrapper around the core service.
https://unbound.docs.nlnetlabs.nl/en/latest/topics/core/performance.html
