### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

### ISSUE THREAD

**Issue by jtommi** [klutchell/unbound-docker#3]
Hi,
I wanted to run a warmup script for unbound, but when I do
`docker exec -ti unbound /bin/bash` (or just bash at the end)
I get this error message:
`OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown`

System:
- Docker 20.10.2, build 2291f61
- Rpi4 2GB
- Raspbian 10 up-to-date

I get the same behaviour with you non-dnscrypt unbound container

**Comment by klutchell** [comment]
Yup, that's to be expected. There is no shell or system utilities in my unbound containers, just the unbound binaries and libraries.

I know this makes them more difficult to work with, but it also makes the images incredibly small and reduces the attack surface.

**Comment by jtommi** [comment]
Oh, thanks for the explanation
