### ISSUE TITLE
Older root.hints in latest Image

### ISSUE THREAD

**Issue by kroehrl** [klutchell/unbound-docker#32]
Hey @klutchell,

thanks for providing that great image.
I just realized, that the root.hints between the following images are now different, the "latest"-Image has an older root.hints file:

_root.hints_ from image with tag __latest__:
> ;       last update:     January 11, 2021 
> ;       related version of root zone:     2021011101

_root.hints_ from image with tag __unbound-1-14-0__:
> ;       last update:     December 07, 2021
> ;       related version of root zone:     2021120701

If I remember correctly, the tags __v1.14.0-r0__ and __v1.14.0-r1__ behave like the __latest__ in that case.

I saw in the Readme this hint as well:
```bash
# optionally update root hints before building
rm rootfs_overlay/etc/unbound/root.hints
wget https://www.internic.net/domain/named.root -O rootfs_overlay/etc/unbound/root.hints
```

But I was wondering that in a newer image version an older version is included. Maybe it wasn't on purpose, so I wanted to let you know ;)

Apart from that, is there a reason why you don't include the (optional) step above in the Dockerfile itself to always have the latest root.hints when building the image?

**Comment by klutchell** [comment]
Good catch, I failed to update root.hints in the main merge. I will open a new PR and add it shortly.

> root.hints from image with tag unbound-1-14-0

This is from a development branch that did not get merged, in fact I should delete it from DockerHub to avoid confusion.

> Apart from that, is there a reason why you don't include the (optional) step above in the Dockerfile itself to always have the latest root.hints when building the image?

Good question! No real reason except that it's one of those things that should be validated by human eyes after running, to ensure that there wasn't some kind of network attack happening during the time of the build. I feel it's safer to have root hints under version control, and it only really needs updating once in a while anyway.

**Comment by kroehrl** [comment]
Awesome! Thank you very much for you quick fix :)

> Good question! No real reason except that it's one of those things that should be validated by human eyes after running, to ensure that there wasn't some kind of network attack happening during the time of the build. I feel it's safer to have root hints under version control, and it only really needs updating once in a while anyway.

Good Argument and valid reason, makes sense. :+1: 

From my perspective, I am fine if you set the issue to resolved - nothing to add from my side.
Keep up the good work ;)
