### ISSUE TITLE
Update unbound to 1.19.1

### ISSUE THREAD

**Issue by churchofnoise** [klutchell/unbound-docker#337]
https://github.com/NLnetLabs/unbound/releases/tag/release-1.19.0

**Comment by klutchell** [comment]
Correct link is https://github.com/NLnetLabs/unbound/releases/tag/release-1.19.1

**Comment by churchofnoise** [comment]
> Correct link is https://github.com/NLnetLabs/unbound/releases/tag/release-1.19.1

Absolutely - my bad, apologies!
