### ISSUE TITLE
OCI runtime exec failed

### ISSUE THREAD

**Issue by JonAnder83** [klutchell/unbound-docker#35]
I'm getting this error on both my docker setups on x86_64 and arm64 (meaning not platform issue):

`OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "drill": executable file not found in $PATH: unknown`

Any suggestion?

**Comment by klutchell** [comment]
Hey @JonAnder83, in the latest v14 release I replaced the `drill` executable in the container with `dig`.

Do you have a custom healthcheck or some other command that is making use of this?

**Comment by JonAnder83** [comment]
Hi! AFAIK, there's no health check. I launch this container in conjunction with pihole.
DNS resolution seems to be working still so I don't really know what's using that drill command.

**Comment by klutchell** [comment]
This repo has no mention of the word drill in it's current state, so it must be something stale. Can you share the output of `docker inspect <unbound_container>`?

**Comment by JonAnder83** [comment]
```
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "drill",
                    "-Qp",
                    "5053",
                    "nlnetlabs.nl",
                    "@127.0.0.1"
                ],
```

That's the interesting part right?
I don't have any health checks configured on my docker file tho. i don't know where that came from nor how to change/remove it :(

```  unbound:
    container_name: unbound
    image: klutchell/unbound
    ports:
      - '5053:5053/udp'
    restart: always
```

**Comment by klutchell** [comment]
Very weird, that is the old healthcheck that I removed over a month ago, so if you are using a recent image without drill, the healthcheck should be gone as well.

It seems like your compose stack hasn't removed the old healthcheck, I wonder if that's a known compose issue?

Can you try changing your compose file to `image: klutchell/unbound:v1.14.0-r4` and see if it recreates the container?

If all else fails it could probably be resolved with `docker-compose down` and `docker-compose up` without any data loss?

**Comment by klutchell** [comment]
Oh, also important to note that since you aren't mounting a config directory the default internal port is now 53.
```
    container_name: unbound
    image: klutchell/unbound:v1.14.0-r4
    ports:
      - '5053:53/udp'
    restart: always
 ```

**Comment by JonAnder83** [comment]
Recreated following your guidelines and now there are no warning errors anymore. That was weird. Thank you!

**Comment by klutchell** [comment]
Weird indeed. Happy holidays!
