### ISSUE TITLE
Enable Cache DB module with Redis backend

### ISSUE THREAD

**Issue by hugochc** [klutchell/unbound-docker#372]
Hi, @klutchell , Is it possible in a future release to enable the cachedb module to be used together with Redis, similar to what was done by crazymax in the repository below?

[https://github.com/crazy-max/docker-unbound#external-backend-db-as-auxiliary-cache](url)

**Comment by klutchell** [comment]
Are you interested in opening a PR with the change?

It appears we need to:
1. Add `--enable-cachedb` to the unbound build configuration in the Dockerfile ([example](https://github.com/crazy-max/docker-unbound/blob/9e8594ee780f164c82b1cc6d5d0c27232190e3d2/Dockerfile#L47C5-L47C21))
2. Test `module-config: "validator cachedb iterator"` in a custom conf file (but probably not make it the default) ([example](https://github.com/crazy-max/docker-unbound/blob/9e8594ee780f164c82b1cc6d5d0c27232190e3d2/rootfs/etc/unbound/unbound.conf#L3))

**Comment by hugochc** [comment]
Thanks to response. According to [Unbound Docs](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#cache-db-module-options), it is also necessary to add `hiredis` dependency and add a new compilation option `--with-libhiredis` to configure support to Redis. I will send a draft to your review.
