### ISSUE TITLE
why running image shows as unhealthy ?

### ISSUE THREAD

**Issue by id4vip** [klutchell/unbound-docker#4]
I am using this image with given instruction. 
"
 run a recursive dns server on host port 53 with an existing host volume
 note that in this case /path/to/config must already contain unbound.conf and
 any other custom files (use ./rootfs_overlay/etc/unbound/ as a reference)
 /path/to/config must also be writable by user 1001
docker run --name unbound-dnscrypt \
  -p 53:53/tcp -p 53:53/udp \
  -v /path/to/config:/etc/unbound \
  klutchell/unbound-dnscrypt
"
I have put all sample files "rootfs_overlay/etc/unbound" (root.hints, root.key, unbound.conf,a-record.conf) in unbound folder. my image is running it resolve queries & my a-record queries. it looks every thing working correctly. but in "docker ps" command this image shows "unhealthy". why this image show unhealthy? is it making any trouble? please guide me how i can make it healthy. 

also in a-records.conf i have write (private-domain: "plex.direct"). but even then the resolve time is more then 200ms. but plex & unbound installed on same machine. it should not be take more 1ms but why it is resolving take time more then 200ms. in my machine adgaurd, unbound, wireguard & plex is installed via docker compose on debian nuc.

**Comment by klutchell** [comment]
You can check the healthcheck logs directly and it may give a hint as to why it is failing.

```bash
docker inspect --format "{{json .State.Health }}" <container name> | jq
```

You could also try running the healthcheck manually to see what it return.

```bash
docker exec <container name> dig sigok.verteiltesysteme.net @127.0.0.1
```

**Comment by id4vip** [comment]
the result of both commands are as below 
root@DietPi:/mnt/2b3e5872-f81d-4a5f-91ad-bfc916090b6c/dietpi_userdata/sonudocker/unbound# docker exec unbound dig sigok.verteiltesysteme.net @127.0.0.1

; <<>> DiG 9.11.22 <<>> sigok.verteiltesysteme.net @127.0.0.1
;; global options: +cmd
;; connection timed out; no servers could be reached




root@DietPi:/mnt/2b3e5872-f81d-4a5f-91ad-bfc916090b6c/dietpi_userdata/sonudocker/unbound# docker inspect --format "{{json .State.Health }}" unbound | jq
-bash: jq: command not found

**Comment by id4vip** [comment]
my docker-compose for both applications are as
"
  adguard:
    image: adguard/adguardhome
    container_name: "adguard"
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=America/Edmonton
    volumes:
      - '${PWD}/adguard/work:/opt/adguardhome/work'
      - '${PWD}/adguard/confdir:/opt/adguardhome/conf'
  unbound:
    image: klutchell/unbound-dnscrypt
    container_name: "unbound"
    restart: unless-stopped
    volumes:
      - '${PWD}/unbound:/etc/unbound'
    ports:
      - '5335:5335/udp'
      - '5335:5335/tcp'
"


I can confirm from windows nslookup command. i can get nuc.local or rpi.local etc. which prove a-record works & adguard upstream  dns 127.0.0.1:5335 works via test & then apply & system resolve yahoo.com etc. in nslookup command on windows pc

**Comment by id4vip** [comment]
root@DietPi:/mnt/2b3e5872-f81d-4a5f-91ad-bfc916090b6c/dietpi_userdata/sonudocker# docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS                      PORTS                                                                                                                                                                         NAMES

ba8fa95b1183   klutchell/unbound-dnscrypt      "unbound"                10 minutes ago   Up 10 minutes (unhealthy)   0.0.0.0:5335->5335/tcp, 0.0.0.0:5335->5335/udp, :::5335->5335/tcp, :::5335->5335/udp

**Comment by klutchell** [comment]
It looks like you changed the unbound listening port from 53 to 5335 so you'll need to update the healthcheck accordingly, or disable it entirely.

```bash
docker exec <container name> dig -p 5335 sigok.verteiltesysteme.net @127.0.0.1
```

**Comment by id4vip** [comment]
The result of this command is 
root@DietPi:~# docker exec unbound dig -p 5335 sigok.verteiltesysteme.net @127.0.0.1

; <<>> DiG 9.11.22 <<>> -p 5335 sigok.verteiltesysteme.net @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2473
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;sigok.verteiltesysteme.net.    IN      A

;; ANSWER SECTION:
sigok.verteiltesysteme.net. 60  IN      A       134.91.78.139

;; Query time: 413 msec
;; SERVER: 127.0.0.1#5335(127.0.0.1)
;; WHEN: Sun May 02 20:48:55 UTC 2021
;; MSG SIZE  rcvd: 71

I try to implement your "https://hub.docker.com/r/klutchell/unbound" methodology. as my server 53 port already consumed by adguard to prevent the port conflict i use 5335 port dedicated for unbound. please guide me how i can stop this health check mechanism or edit accordingly. as if it will working one time no body in my home going to change anything on server so i think no need to  health check. it feel unpleasant if docker image complaint me that image is unhealthy.

**Comment by klutchell** [comment]
You can disable the healthcheck in your docker compose file:
https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

```
unbound:
  image: klutchell/unbound-dnscrypt
  container_name: "unbound"
  restart: unless-stopped
  volumes:
    - '${PWD}/unbound:/etc/unbound'
  ports:
    - '5335:5335/udp'
    - '5335:5335/tcp'
  healthcheck:
    disable: true
  ```

**Comment by id4vip** [comment]
Thanks klutchell, I have implement 
"  healthcheck:
    disable: true
"
everything work accordingly, now it not showing me any unhealthy complaint. thanks for your hardwork.
