### ISSUE TITLE
CacheDB does not seem to be enabled when compiled 

### ISSUE THREAD

**Issue by seanob86** [klutchell/unbound-docker#408]
I have updated to the latest docker image `1.19.3`
Enabled the cachedb module in my custom config `module-config: "validator cachedb iterator" `
Configured a `cachedb.conf` in custom config directory with redis cache server details

Start the docker image, and this error is found:

```
[1711797232] unbound[1:0] error: packets timestamping is not supported on this platform
[1711797232] unbound[1:0] warning: socket timestamping is not available
[1711797233] unbound[1:0] error: Unknown value in module-config, module: 'cachedb'. This module is not present (not compiled in), See the list of linked modules with unbound -V
[1711797233] unbound[1:0] fatal error: failed to setup modules
```

Unbound documentation states that the daemon be compiled with `-- enable-cachedb`. I do not see this compile option used in the `Dockerfile` and neither is it found when executing `unbound -V`

```
Version 1.19.3

Configure line: --prefix=/opt/usr --with-conf-file=/etc/unbound/unbound.conf --with-run-dir=/var/unbound --with-chroot-dir=/var/unbound --with-pidfile=/var/unbound/unbound.pid --with-rootkey-file=/var/unbound/root.key --disable-static --disable-shared --disable-rpath --enable-dnscrypt --enable-subnet --with-pthreads --with-libevent --with-ssl --with-username=unbound
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.1.4 24 Oct 2023
Linked modules: dns64 subnetcache respip validator iterator
DNSCrypt feature available
```

```
Cache DB Module Options
       The Cache DB module must be configured in the module-config: "validator
       cachedb  iterator" directive and be compiled into the daemon with --en-
       able-cachedb.
```

**Comment by klutchell** [comment]
Hey @seanob86 , currently this feature is only enabled in the main tag. It will be included in the next unbound release tag whenever that comes.

I've also added a comment to the original PR to see if we are missing a flag, but in the meantime I suggest trying klutchell/unbound:main

**Comment by seanob86** [comment]
Thanks and sorry, I must have missed that detail about the `main` tag.
Can confirm `main` tag works!
