### ISSUE TITLE
cachedb support

### ISSUE THREAD

**Issue by Qeynos** [klutchell/unbound-docker#46]
I want save cache in redis, tried a lot but failed, please help if possible

**Comment by quyleanh** [comment]
@Qeynos did you resolve it? Could you please share your method?
Sorry for mentioning you too @klutchell

**Comment by Qeynos** [comment]
> @Qeynos did you resolve it? Could you please share your method?
> Sorry for mentioning you too @klutchell

Try this
https://github.com/Qeynos/unbound-redis-Docker/blob/main/unbound-redis-scratch/Dockerfile

and I have build images in hub docker com

**Comment by quyleanh** [comment]
> > @Qeynos did you resolve it? Could you please share your method?
> > Sorry for mentioning you too @klutchell
> 
> Try this https://github.com/Qeynos/unbound-redis-Docker/blob/main/unbound-redis-scratch/Dockerfile
> 
> and I have build images in hub docker com

Thank you for your quick reply. I haven't checked your docker file yet, but do you have `prefetch` option on your build?

```
   prefetch: <yes or no>
          If yes, message cache elements are prefetched before they expire
          to keep the cache up to date.  Default is  no.   Turning  it  on
          gives about 10 percent more traffic and load on the machine, but
          popular items do not expire from the cache.
```

**Comment by churchofnoise** [comment]
@Qeynos : might be useful to also indicate that your image forwards to Google and Cloudflare iso doing recursive resolving, using the authoritative servers.

**Comment by quyleanh** [comment]
@churchofnoise could you explain more detail?

**Comment by Qeynos** [comment]
@quyleanh no conf file in the build, you need to set for your self
https://hub.docker.com/r/qeynos/unbound-redis-scratch

**Comment by quyleanh** [comment]
@Qeynos thank you very much. Your current config has enabled prefetch.

**Comment by quyleanh** [comment]
@churchofnoise I see your point. Unbound should recursively resolve query instead of forward to upstream DNS resolver, shouldn't it?
