### ISSUE TITLE
Slow?

### ISSUE THREAD

**Issue by vespino** [klutchell/unbound-docker#473]
Are there issues with the latest version? My queries seem a lot slower than before. Haven’t had time to roll back and test.

**Comment by klutchell** [comment]
I haven't noticed any issues, have you looked for issues/comments on the upstream project? It's likely not related to the container.

**Comment by vespino** [comment]
I haven’t, but I will.

**Comment by vespino** [comment]
I have installed the latest version and the slow issues seem to have been resolved.
