### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by DFlexy** [klutchell/unbound-docker#49]
Good afternoon,
Sorry if I posted in the wrong place

I have a doubt..
What is the difference between the 2 unbound below?

https://hub.docker.com/r/klutchell/unbound
https://hub.docker.com/r/klutchell/unbound-dnscrypt

**Comment by klutchell** [comment]
Great question! This is the current deploy location: https://hub.docker.com/r/klutchell/unbound

https://hub.docker.com/r/klutchell/unbound-dnscrypt is the old repo and is no longer updated. I could probably change my deploy tools to push to both but I would rather deprecate [unbound-dnscrypt](https://hub.docker.com/r/klutchell/unbound-dnscrypt) I think.
