### ISSUE TITLE
forward-zone

### ISSUE THREAD

**Issue by rochmind** [klutchell/unbound-docker#5]
unbound is setup as pihole's upstream dns and both running as docker containers. works ok except for work machine when working from home, ms teams and zoom comes back with dns request timeouts.

would adding forward requests to for recursion e.g. 1.1.1.1 enable this via forward-zone? there is no shell to cli and test this config

**Comment by klutchell** [comment]
Do other devices on the same network resolve DNS okay? Are you manually setting the DNS server on each client or is your DHCP server handing out the DNS servers?

You might have better luck asking this question on the Pi-Hole forums.

**Comment by rochmind** [comment]
all other devices work ok and the router is the dhcp server with auto dns. if cloudfare is the upstream dns, my work machine (uses vpn) works but if i set unbound as upstream, only that device is timing out. what is even weirder is email and internet work except collab tools. will try to do a build so i can figure out error

**Comment by klutchell** [comment]
If your work machine is on a VPN then it won't be able to query DNS on the local subnet, that would be considered a DNS leak.

I expect if you disconnect your VPN the local DNS lookup will work. You'll have to use a public DNS server while connected to your work VPN, or a DNS server on your workplace network.

**Comment by rochmind** [comment]
work machine uses one of them new tech where each ip connection is tunneled and it uses my local dns - i can see it in the logs
