### ISSUE TITLE
Make unbound.conf available for tweaking

### ISSUE THREAD

**Issue by churchofnoise** [klutchell/unbound-docker#56]
Hi Kyle,

I've got your docker file running on my Firewalla Purple, and would like to be able to edit the unbound.conf file.
Could you please indicate which code I'd have to add to my yaml file to enable that please?

Thanks!

**Comment by klutchell** [comment]
Hey @churchofnoise, I've never used that product before but based on their documentation you can mount locally directories as volumes like any other docker-compose stack.

So try adding something like this to your unbound service definition:

```yml
  volumes:
      - '/data/unbound/etc-unbound/:/etc/unbound/'
 ```
 
Then before running you can grab the default configuration files from here and put them in `/data/unbound/etc-unbound/` on your firewalll.
https://github.com/klutchell/unbound-docker/tree/main/rootfs_overlay/etc/unbound

Then you can modify as needed.

**Comment by churchofnoise** [comment]
@klutchell Thanks! I'll play around a bit with it.

FYI, I've mentioned your docker image for Unbound on the Firewalla community after a couple of us had been looking for ways to get Pi-Hole and Unbound running on it ( https://help.firewalla.com/hc/en-us/community/posts/1500001172701/comments/4941267404435 ). Very grateful you provide this multiarch image that acts as a recursive resolver!
