### ISSUE TITLE
HELP IPv6

### ISSUE THREAD

**Issue by DFlexy** [klutchell/unbound-docker#58]
Kyle Harding good afternoon.
Sorry if I posted in the wrong place.

But I need some help to configure IPv6
I use pihole + unbound (BRIDGE) follow my settings

```
==================================================
docker network create \
  --driver=bridge \
  --subnet=172.20.0.0/24 \
  --gateway=172.20.0.254 \
  lan
==================================================
docker run -d \
  --name=pihole \
  --hostname=pihole \
  -e TZ=America/Maceio \
  -e FTLCONF_REPLY_ADDR4=172.30.0.254 \
  -e FTLCONF_REPLY_ADDR6=fd51:42f8:caae:d92e::ff \
  -e DHCP_ACTIVE=true \
  -e DHCP_START=172.30.0.100 \
  -e DHCP_END=172.30.0.200 \
  -e DHCP_ROUTER=172.30.0.1 \
  -e DHCP_IPv6=true \
  -e PIHOLE_DNS_=172.20.0.2 \
  -e DNSMASQ_LISTENING=bind \
  -e WEBUIBOXEDLAYOUT=traditional \
  -e WEBTHEME=default-dark \
  -e DHCP_rapid_commit=true \
  -e VIRTUAL_HOST="pi.hole" \
  -e DNSMASQ_USER=root \
  -v pihole:/etc/pihole/ \
  -v dnsmasq:/etc/dnsmasq.d/ \
  --cap-add=NET_ADMIN \
  --cap-add=CAP_SYS_NICE \
  --network=host \
  --restart=unless-stopped \
  pihole/pihole:nightly
==================================================
docker run -d \
  --name unbound \
  --hostname unbound \
  --network=lan \
  --ip=172.20.0.2 \
  --restart=unless-stopped \
  --cap-add=NET_ADMIN \
  --cap-add=CAP_SYS_NICE \
  -v unbound:/etc/unbound/ \
  klutchell/unbound:latest
==================================================
```

**Comment by klutchell** [comment]
Hey @DFlexy, good to hear from you again.

I'll start by saying I have almost no experience configuring IPv6 and I don't use it at home myself, so I may not be of much assistance. Maybe other users will see this thread and speak up.

Can you help me by stating your exact goal, and what went wrong with what you've tried?

**Comment by DFlexy** [comment]
Apparently I managed to make it work I believe but I didn't get validity yet.
But I'm seeing duplicate queries on ipv4 and ipv6



![image](https://user-images.githubusercontent.com/50220928/161126091-1271cf6b-09b0-4ae7-9aac-6cc6b3e41f17.png)

**Comment by klutchell** [comment]
Have you tried disabling IPv4 in Pi-hole and/or `unbound.conf` to remove the duplicates?

**Comment by DFlexy** [comment]
Dont work more ty for   try help rsrsr ;)
