### ISSUE TITLE
Update to Unbound 1.16.0

### ISSUE THREAD

**Issue by churchofnoise** [klutchell/unbound-docker#64]
Hi!
Would it please be possible to update the container to the latest unbound version, 1.16.0 which was released today?
Thanks!

**Comment by klutchell** [comment]
Sure thing, I'll work on that today and let you know when I have a version for testing!

**Comment by klutchell** [comment]
The new version is working for me, can you give the `klutchell/unbound:pr-65` tag a try before I merge?

**Comment by churchofnoise** [comment]
Just updated my container and seems to run fine!
Any tests I can do to further confirm?

**Comment by klutchell** [comment]
That should be enough, the automated tests are passing too.

I'll merge it now and label the release when I'm back at my desk.
