### ISSUE TITLE
Custom conf file seems no longer loaded since moving the 'include' clause out of the 'server:' section of unbound.conf

### ISSUE THREAD

**Issue by churchofnoise** [klutchell/unbound-docker#70]
It seems that the files in the directory with custom conf files are not driving the expected outcome, since the recent change in the unbound.conf that moved it out of the 'server:' section of the file.
This e.g. showed in the Pi-Hole web interface (Pi-hole is configured to use the Unbound docker as DNS server): the percentage of responses from cache went down to a very low level, whereas before it was quite high as I had configured min-ttl at 86400.
(I verified this by checking the TTL of a domain I digged: I configured cache-min-ttl at 86400 yet the domain showed a ttl of 60)

The config file remained in the same location, and its contents remained unchanged, except for an addition of an auth-zone section (I used this before and it never impacted cache performance).

Could this be because the reference to the folder with the custom configs comes before the server section in unbound.conf?
I looked into the official documentation but found no specific indication.
Any chance you'd consider moving the include part to the end of the unbound.conf file please?

**Comment by klutchell** [comment]
> Any chance you'd consider moving the include part to the end of the unbound.conf file please?

I saw your PR but have you confirmed this actually fixes the issue? I would like to understand why it doesn't work today.

**Comment by churchofnoise** [comment]
Makes a lot of sense.

I've just tried by commenting out the non-'server' part of my custom config, with no effect.
In the mean time, I'm asking the Unbound community here: https://github.com/NLnetLabs/unbound/issues/710 

Wouter Wijngaards already responded: https://github.com/NLnetLabs/unbound/issues/710#issuecomment-1173627501 

So here is my takeaway:

- change 'include:...' to `include-toplevel: "/etc/unbound/custom.conf.d/*.conf"`: this starts a new toplevel and avoids cases where your custom conf depends on which section is opened in the 'mother' file, so in a way it is cleaner but not absolutely necessary. This is mentioned in the Unbound manual:

>        For a more structural include option, the  include-toplevel:  directive
>        can  be used.  This closes whatever clause is currently active (if any)
>        and forces the use of clauses in the included  files  and  right  after
>        this directive.

- move it to the end of your file, as I understood that later statements can override earlier ones. So if someone wanted to alter one of your configurations (change verbosity, activate 'use-caps-for-id', ...) that would make that possible. This is what's mentioned in the Unbound manual:

>        Files  can be included using the include: directive. It can appear any-
>        where, it accepts a single file name as argument.  Processing continues
>        as  if  the text from the included file was copied into the config file
>        at that point.  If also using chroot, using full path names for the in-
>        cluded  files  works, relative pathnames for the included names work if
>        the directory where the daemon is started equals its chroot/working di-
>        rectory  or  is  specified before the include statement with directory:
>        dir. 

What do you think?

**Comment by klutchell** [comment]
Sounds good to me, thanks for looking into this!

**Comment by churchofnoise** [comment]
Just wanted to confirm it works perfectly!
Thanks a lot!
