### ISSUE TITLE
healtcheck is not possible

### ISSUE THREAD

**Issue by zilexa** [klutchell/unbound-docker#77]
On host Manjaro Gnome, Intel based system: 

```
OCI runtime exec failed: exec failed: unable to start container process: exec: "dig -p 5335 sigok.verteiltesysteme.net @127.0.0.1": executable file not found in $PATH: unknown
```
When I try to access console of the container via Portainer, I can't. 
Tried both bash and sh. This is why this error appears. Nothing can be executed.

The image itself works just fine, just cannot access console and cannot run healthcheck commands.

**Comment by klutchell** [comment]
Hey @zilexa, this image is [distroless](https://github.com/GoogleContainerTools/distroless), so it does not contain a shell or any other tools you could use with exec.

> "Distroless" images contain only your application and its runtime dependencies. They do not contain package managers, shells or any other programs you would expect to find in a standard Linux distribution.

This is why the healthcheck example I have in the README isn't working. The `--health-cmd` flag attempts to wrap the command in `/bin/sh -c` but `sh` doesn't exist and you get the error you're seeing.

However, you can still [use docker-compose to specify a healthcheck](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck) using the `CMD` prefix (not `CMD-SHELL`).

I'll update the README examples accordingly, sorry for the confusion.

**Comment by zilexa** [comment]
Thanks! That makes sense. I'll wait for the updated documentation and will give it a go.
