### ISSUE TITLE
Unable to get local-zone and local-data working

### ISSUE THREAD

**Issue by sgtcoder** [klutchell/unbound-docker#99]
Creating a new file `a-records.conf` in /root/unbound with the default unbound.conf from the docker.

```
docker run \
  --name=unbound-dnscrypt \
  -p 53:53/tcp -p 53:53/udp \
  -v /root/unbound:/etc/unbound/custom.conf.d \
  klutchell/unbound-dnscrypt
```
```
server:
    local-zone: "doubleclick.net" redirect
    local-data: "doubleclick.net A 127.0.0.1"
```
```
nslookup doubleclick.net DOCKER_IP
```

I am not getting the 127.0.0.1 IP address, instead I am getting a Non-authoritative answer:.

Is there something I have to enable to get this working? I have been researching for a bit of time now and can't find anything.

**Comment by sgtcoder** [comment]
For some reason if I use the non dnscrypt version, DNSSEC and local lookups work now

```
docker run \
  --name=unbound \
  -p 53:53/tcp -p 53:53/udp \
  -v /root/unbound:/etc/unbound/custom.conf.d \
  klutchell/unbound
```

**Comment by klutchell** [comment]
Hey there, `klutchell/unbound-dnscrypt` is the old name for this project and has not received updates for over 10 months. You should be using the `klutchell/unbound` image which seems to be working for you!

I'll add a note to the old DockerHub page and close this issue.

**Comment by sgtcoder** [comment]
Thank you, one last thing, and it probably should go in a different thread.
```
[1664386290] unbound[1:0] warning: too many file descriptors requested. The builtinmini-event cannot handle more than 1024. Config for less fds or compile with libevent
```

How do I install libevent in the docker with rootfs?

**Comment by klutchell** [comment]
The recent releases of `klutchell/unbound` are using libevent so you should not see this warning.

**Comment by sgtcoder** [comment]
Thank you. Sorry, yah I accidently was pasting the old dnscrypt version again. Everything seems to be good. I am coming from a custom dnsmasq and was getting 30ms, and this is giving me like 6ms so that's much quicker. Also, Android requires DNSSEC.
